name: Spring Boot CI/CD Pipeline
on: push
jobs:
    springboot-workflow:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v5

            - run: ./gradlew bootjar

            - name: Build with Gradle
              run: cd /webapp &&./gradlew build

            - name: Build Docker Image
              run: docker build -t springboot-webapp:webapp-latest ./webapp

            - run: docker images