name: Spring Boot CI/CD Pipeline
on: push
jobs:
    springboot-workflow:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v5

            - name: Build JAR with Gradle
              run: ./gradlew bootjar
              working-directory: ./webapp

            - name: Build with Gradle
              run: ./gradlew build
              working-directory: ./webapp

            - name: Build Docker Image
              run: docker build -t springboot-webapp:webapp-latest ./webapp

            - name: List Docker Images
              run: docker images