name: Spring Boot CI/CD Pipeline
on: push
permissions:
  packages: write
jobs:
    springboot-workflow:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v5

            - name: Build JAR with Gradle
              run: ./gradlew bootjar
              working-directory: ./webapp

            - name: Build with Gradle
              run: ./gradlew build
              working-directory: ./webapp

            - name: Build Docker Image
              run: |
                docker build -t springboot-webapp:webapp-latest ./webapp
              
                
            - name: set lowercase username 
              run: echo "OWNER_LOWER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV    

            - name: Log in to GitHub Container Registry
              run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            
            - name: tag docker image
              run:  docker tag springboot-webapp:webapp-latest ghcr.io/${OWNER_LOWER}/springboot-webapp:webapp-latest 


            - name: List Docker Images
              run: docker images

            - name: Push Docker Image to GitHub Container Registry
              run: docker push ghcr.io/${OWNER_LOWER}/springboot-webapp:webapp-latest